/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as DashboardRouteImport } from "./routes/_dashboard"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as DashboardIndexRouteImport } from "./routes/_dashboard/index"
import { Route as DashboardTeamsRouteImport } from "./routes/_dashboard/teams"
import { Route as DashboardTeamChatRouteImport } from "./routes/_dashboard/team-chat"
import { Route as DashboardTasksRouteImport } from "./routes/_dashboard/tasks"
import { Route as DashboardSettingsRouteImport } from "./routes/_dashboard/settings"
import { Route as DashboardProjectsRouteImport } from "./routes/_dashboard/projects"
import { Route as DashboardProfileRouteImport } from "./routes/_dashboard/profile"
import { Route as DashboardMilestonesRouteImport } from "./routes/_dashboard/milestones"
import { Route as DashboardMeetingRouteImport } from "./routes/_dashboard/meeting"
import { Route as DashboardIdeaHubRouteImport } from "./routes/_dashboard/idea-hub"
import { Route as DashboardFilesRouteImport } from "./routes/_dashboard/files"
import { Route as DashboardAnalyticsRouteImport } from "./routes/_dashboard/analytics"
import { Route as DashboardAiToolsRouteImport } from "./routes/_dashboard/ai-tools"
import { Route as DashboardAiChatRouteImport } from "./routes/_dashboard/ai-chat"
import { Route as AuthSignUpRouteImport } from "./routes/_auth/sign-up"
import { Route as AuthSignInRouteImport } from "./routes/_auth/sign-in"
import { Route as DashboardSettingsIndexRouteImport } from "./routes/_dashboard/settings.index"
import { Route as DashboardProfileIndexRouteImport } from "./routes/_dashboard/profile.index"
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$"
import { Route as DashboardSettingsUsageRouteImport } from "./routes/_dashboard/settings.usage"
import { Route as DashboardSettingsSecurityRouteImport } from "./routes/_dashboard/settings.security"
import { Route as DashboardSettingsRolesRouteImport } from "./routes/_dashboard/settings.roles"
import { Route as DashboardSettingsMembersRouteImport } from "./routes/_dashboard/settings.members"
import { Route as DashboardSettingsInvoicesRouteImport } from "./routes/_dashboard/settings.invoices"
import { Route as DashboardSettingsIntegrationsRouteImport } from "./routes/_dashboard/settings.integrations"
import { Route as DashboardSettingsBillingRouteImport } from "./routes/_dashboard/settings.billing"
import { Route as DashboardSettingsApiKeysRouteImport } from "./routes/_dashboard/settings.api-keys"
import { Route as DashboardProfileSecurityRouteImport } from "./routes/_dashboard/profile.security"
import { Route as DashboardProfilePreferencesRouteImport } from "./routes/_dashboard/profile.preferences"
import { Route as DashboardProfileNotificationsRouteImport } from "./routes/_dashboard/profile.notifications"

const DashboardRoute = DashboardRouteImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: "/teams",
  path: "/teams",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamChatRoute = DashboardTeamChatRouteImport.update({
  id: "/team-chat",
  path: "/team-chat",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMilestonesRoute = DashboardMilestonesRouteImport.update({
  id: "/milestones",
  path: "/milestones",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMeetingRoute = DashboardMeetingRouteImport.update({
  id: "/meeting",
  path: "/meeting",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIdeaHubRoute = DashboardIdeaHubRouteImport.update({
  id: "/idea-hub",
  path: "/idea-hub",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFilesRoute = DashboardFilesRouteImport.update({
  id: "/files",
  path: "/files",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiToolsRoute = DashboardAiToolsRouteImport.update({
  id: "/ai-tools",
  path: "/ai-tools",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiChatRoute = DashboardAiChatRouteImport.update({
  id: "/ai-chat",
  path: "/ai-chat",
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => AuthRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardProfileRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsUsageRoute = DashboardSettingsUsageRouteImport.update({
  id: "/usage",
  path: "/usage",
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: "/security",
    path: "/security",
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsRolesRoute = DashboardSettingsRolesRouteImport.update({
  id: "/roles",
  path: "/roles",
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsMembersRoute =
  DashboardSettingsMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsInvoicesRoute =
  DashboardSettingsInvoicesRouteImport.update({
    id: "/invoices",
    path: "/invoices",
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsIntegrationsRoute =
  DashboardSettingsIntegrationsRouteImport.update({
    id: "/integrations",
    path: "/integrations",
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: "/billing",
    path: "/billing",
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsApiKeysRoute =
  DashboardSettingsApiKeysRouteImport.update({
    id: "/api-keys",
    path: "/api-keys",
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardProfileSecurityRoute =
  DashboardProfileSecurityRouteImport.update({
    id: "/security",
    path: "/security",
    getParentRoute: () => DashboardProfileRoute,
  } as any)
const DashboardProfilePreferencesRoute =
  DashboardProfilePreferencesRouteImport.update({
    id: "/preferences",
    path: "/preferences",
    getParentRoute: () => DashboardProfileRoute,
  } as any)
const DashboardProfileNotificationsRoute =
  DashboardProfileNotificationsRouteImport.update({
    id: "/notifications",
    path: "/notifications",
    getParentRoute: () => DashboardProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof DashboardIndexRoute
  "/sign-in": typeof AuthSignInRoute
  "/sign-up": typeof AuthSignUpRoute
  "/ai-chat": typeof DashboardAiChatRoute
  "/ai-tools": typeof DashboardAiToolsRoute
  "/analytics": typeof DashboardAnalyticsRoute
  "/files": typeof DashboardFilesRoute
  "/idea-hub": typeof DashboardIdeaHubRoute
  "/meeting": typeof DashboardMeetingRoute
  "/milestones": typeof DashboardMilestonesRoute
  "/profile": typeof DashboardProfileRouteWithChildren
  "/projects": typeof DashboardProjectsRoute
  "/settings": typeof DashboardSettingsRouteWithChildren
  "/tasks": typeof DashboardTasksRoute
  "/team-chat": typeof DashboardTeamChatRoute
  "/teams": typeof DashboardTeamsRoute
  "/profile/notifications": typeof DashboardProfileNotificationsRoute
  "/profile/preferences": typeof DashboardProfilePreferencesRoute
  "/profile/security": typeof DashboardProfileSecurityRoute
  "/settings/api-keys": typeof DashboardSettingsApiKeysRoute
  "/settings/billing": typeof DashboardSettingsBillingRoute
  "/settings/integrations": typeof DashboardSettingsIntegrationsRoute
  "/settings/invoices": typeof DashboardSettingsInvoicesRoute
  "/settings/members": typeof DashboardSettingsMembersRoute
  "/settings/roles": typeof DashboardSettingsRolesRoute
  "/settings/security": typeof DashboardSettingsSecurityRoute
  "/settings/usage": typeof DashboardSettingsUsageRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
  "/profile/": typeof DashboardProfileIndexRoute
  "/settings/": typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof DashboardIndexRoute
  "/sign-in": typeof AuthSignInRoute
  "/sign-up": typeof AuthSignUpRoute
  "/ai-chat": typeof DashboardAiChatRoute
  "/ai-tools": typeof DashboardAiToolsRoute
  "/analytics": typeof DashboardAnalyticsRoute
  "/files": typeof DashboardFilesRoute
  "/idea-hub": typeof DashboardIdeaHubRoute
  "/meeting": typeof DashboardMeetingRoute
  "/milestones": typeof DashboardMilestonesRoute
  "/projects": typeof DashboardProjectsRoute
  "/tasks": typeof DashboardTasksRoute
  "/team-chat": typeof DashboardTeamChatRoute
  "/teams": typeof DashboardTeamsRoute
  "/profile/notifications": typeof DashboardProfileNotificationsRoute
  "/profile/preferences": typeof DashboardProfilePreferencesRoute
  "/profile/security": typeof DashboardProfileSecurityRoute
  "/settings/api-keys": typeof DashboardSettingsApiKeysRoute
  "/settings/billing": typeof DashboardSettingsBillingRoute
  "/settings/integrations": typeof DashboardSettingsIntegrationsRoute
  "/settings/invoices": typeof DashboardSettingsInvoicesRoute
  "/settings/members": typeof DashboardSettingsMembersRoute
  "/settings/roles": typeof DashboardSettingsRolesRoute
  "/settings/security": typeof DashboardSettingsSecurityRoute
  "/settings/usage": typeof DashboardSettingsUsageRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
  "/profile": typeof DashboardProfileIndexRoute
  "/settings": typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_auth": typeof AuthRouteWithChildren
  "/_dashboard": typeof DashboardRouteWithChildren
  "/_auth/sign-in": typeof AuthSignInRoute
  "/_auth/sign-up": typeof AuthSignUpRoute
  "/_dashboard/ai-chat": typeof DashboardAiChatRoute
  "/_dashboard/ai-tools": typeof DashboardAiToolsRoute
  "/_dashboard/analytics": typeof DashboardAnalyticsRoute
  "/_dashboard/files": typeof DashboardFilesRoute
  "/_dashboard/idea-hub": typeof DashboardIdeaHubRoute
  "/_dashboard/meeting": typeof DashboardMeetingRoute
  "/_dashboard/milestones": typeof DashboardMilestonesRoute
  "/_dashboard/profile": typeof DashboardProfileRouteWithChildren
  "/_dashboard/projects": typeof DashboardProjectsRoute
  "/_dashboard/settings": typeof DashboardSettingsRouteWithChildren
  "/_dashboard/tasks": typeof DashboardTasksRoute
  "/_dashboard/team-chat": typeof DashboardTeamChatRoute
  "/_dashboard/teams": typeof DashboardTeamsRoute
  "/_dashboard/": typeof DashboardIndexRoute
  "/_dashboard/profile/notifications": typeof DashboardProfileNotificationsRoute
  "/_dashboard/profile/preferences": typeof DashboardProfilePreferencesRoute
  "/_dashboard/profile/security": typeof DashboardProfileSecurityRoute
  "/_dashboard/settings/api-keys": typeof DashboardSettingsApiKeysRoute
  "/_dashboard/settings/billing": typeof DashboardSettingsBillingRoute
  "/_dashboard/settings/integrations": typeof DashboardSettingsIntegrationsRoute
  "/_dashboard/settings/invoices": typeof DashboardSettingsInvoicesRoute
  "/_dashboard/settings/members": typeof DashboardSettingsMembersRoute
  "/_dashboard/settings/roles": typeof DashboardSettingsRolesRoute
  "/_dashboard/settings/security": typeof DashboardSettingsSecurityRoute
  "/_dashboard/settings/usage": typeof DashboardSettingsUsageRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
  "/_dashboard/profile/": typeof DashboardProfileIndexRoute
  "/_dashboard/settings/": typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/sign-in"
    | "/sign-up"
    | "/ai-chat"
    | "/ai-tools"
    | "/analytics"
    | "/files"
    | "/idea-hub"
    | "/meeting"
    | "/milestones"
    | "/profile"
    | "/projects"
    | "/settings"
    | "/tasks"
    | "/team-chat"
    | "/teams"
    | "/profile/notifications"
    | "/profile/preferences"
    | "/profile/security"
    | "/settings/api-keys"
    | "/settings/billing"
    | "/settings/integrations"
    | "/settings/invoices"
    | "/settings/members"
    | "/settings/roles"
    | "/settings/security"
    | "/settings/usage"
    | "/api/auth/$"
    | "/profile/"
    | "/settings/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/sign-in"
    | "/sign-up"
    | "/ai-chat"
    | "/ai-tools"
    | "/analytics"
    | "/files"
    | "/idea-hub"
    | "/meeting"
    | "/milestones"
    | "/projects"
    | "/tasks"
    | "/team-chat"
    | "/teams"
    | "/profile/notifications"
    | "/profile/preferences"
    | "/profile/security"
    | "/settings/api-keys"
    | "/settings/billing"
    | "/settings/integrations"
    | "/settings/invoices"
    | "/settings/members"
    | "/settings/roles"
    | "/settings/security"
    | "/settings/usage"
    | "/api/auth/$"
    | "/profile"
    | "/settings"
  id:
    | "__root__"
    | "/_auth"
    | "/_dashboard"
    | "/_auth/sign-in"
    | "/_auth/sign-up"
    | "/_dashboard/ai-chat"
    | "/_dashboard/ai-tools"
    | "/_dashboard/analytics"
    | "/_dashboard/files"
    | "/_dashboard/idea-hub"
    | "/_dashboard/meeting"
    | "/_dashboard/milestones"
    | "/_dashboard/profile"
    | "/_dashboard/projects"
    | "/_dashboard/settings"
    | "/_dashboard/tasks"
    | "/_dashboard/team-chat"
    | "/_dashboard/teams"
    | "/_dashboard/"
    | "/_dashboard/profile/notifications"
    | "/_dashboard/profile/preferences"
    | "/_dashboard/profile/security"
    | "/_dashboard/settings/api-keys"
    | "/_dashboard/settings/billing"
    | "/_dashboard/settings/integrations"
    | "/_dashboard/settings/invoices"
    | "/_dashboard/settings/members"
    | "/_dashboard/settings/roles"
    | "/_dashboard/settings/security"
    | "/_dashboard/settings/usage"
    | "/api/auth/$"
    | "/_dashboard/profile/"
    | "/_dashboard/settings/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_dashboard": {
      id: "/_dashboard"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_dashboard/": {
      id: "/_dashboard/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/teams": {
      id: "/_dashboard/teams"
      path: "/teams"
      fullPath: "/teams"
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/team-chat": {
      id: "/_dashboard/team-chat"
      path: "/team-chat"
      fullPath: "/team-chat"
      preLoaderRoute: typeof DashboardTeamChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/tasks": {
      id: "/_dashboard/tasks"
      path: "/tasks"
      fullPath: "/tasks"
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/settings": {
      id: "/_dashboard/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/projects": {
      id: "/_dashboard/projects"
      path: "/projects"
      fullPath: "/projects"
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/profile": {
      id: "/_dashboard/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/milestones": {
      id: "/_dashboard/milestones"
      path: "/milestones"
      fullPath: "/milestones"
      preLoaderRoute: typeof DashboardMilestonesRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/meeting": {
      id: "/_dashboard/meeting"
      path: "/meeting"
      fullPath: "/meeting"
      preLoaderRoute: typeof DashboardMeetingRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/idea-hub": {
      id: "/_dashboard/idea-hub"
      path: "/idea-hub"
      fullPath: "/idea-hub"
      preLoaderRoute: typeof DashboardIdeaHubRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/files": {
      id: "/_dashboard/files"
      path: "/files"
      fullPath: "/files"
      preLoaderRoute: typeof DashboardFilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/analytics": {
      id: "/_dashboard/analytics"
      path: "/analytics"
      fullPath: "/analytics"
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/ai-tools": {
      id: "/_dashboard/ai-tools"
      path: "/ai-tools"
      fullPath: "/ai-tools"
      preLoaderRoute: typeof DashboardAiToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/ai-chat": {
      id: "/_dashboard/ai-chat"
      path: "/ai-chat"
      fullPath: "/ai-chat"
      preLoaderRoute: typeof DashboardAiChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_auth/sign-up": {
      id: "/_auth/sign-up"
      path: "/sign-up"
      fullPath: "/sign-up"
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/sign-in": {
      id: "/_auth/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_dashboard/settings/": {
      id: "/_dashboard/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    "/_dashboard/profile/": {
      id: "/_dashboard/profile/"
      path: "/"
      fullPath: "/profile/"
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardProfileRoute
    }
    "/api/auth/$": {
      id: "/api/auth/$"
      path: "/api/auth/$"
      fullPath: "/api/auth/$"
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_dashboard/settings/usage": {
      id: "/_dashboard/settings/usage"
      path: "/usage"
      fullPath: "/settings/usage"
      preLoaderRoute: typeof DashboardSettingsUsageRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    "/_dashboard/settings/security": {
      id: "/_dashboard/settings/security"
      path: "/security"
      fullPath: "/settings/security"
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    "/_dashboard/settings/roles": {
      id: "/_dashboard/settings/roles"
      path: "/roles"
      fullPath: "/settings/roles"
      preLoaderRoute: typeof DashboardSettingsRolesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    "/_dashboard/settings/members": {
      id: "/_dashboard/settings/members"
      path: "/members"
      fullPath: "/settings/members"
      preLoaderRoute: typeof DashboardSettingsMembersRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    "/_dashboard/settings/invoices": {
      id: "/_dashboard/settings/invoices"
      path: "/invoices"
      fullPath: "/settings/invoices"
      preLoaderRoute: typeof DashboardSettingsInvoicesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    "/_dashboard/settings/integrations": {
      id: "/_dashboard/settings/integrations"
      path: "/integrations"
      fullPath: "/settings/integrations"
      preLoaderRoute: typeof DashboardSettingsIntegrationsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    "/_dashboard/settings/billing": {
      id: "/_dashboard/settings/billing"
      path: "/billing"
      fullPath: "/settings/billing"
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    "/_dashboard/settings/api-keys": {
      id: "/_dashboard/settings/api-keys"
      path: "/api-keys"
      fullPath: "/settings/api-keys"
      preLoaderRoute: typeof DashboardSettingsApiKeysRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    "/_dashboard/profile/security": {
      id: "/_dashboard/profile/security"
      path: "/security"
      fullPath: "/profile/security"
      preLoaderRoute: typeof DashboardProfileSecurityRouteImport
      parentRoute: typeof DashboardProfileRoute
    }
    "/_dashboard/profile/preferences": {
      id: "/_dashboard/profile/preferences"
      path: "/preferences"
      fullPath: "/profile/preferences"
      preLoaderRoute: typeof DashboardProfilePreferencesRouteImport
      parentRoute: typeof DashboardProfileRoute
    }
    "/_dashboard/profile/notifications": {
      id: "/_dashboard/profile/notifications"
      path: "/notifications"
      fullPath: "/profile/notifications"
      preLoaderRoute: typeof DashboardProfileNotificationsRouteImport
      parentRoute: typeof DashboardProfileRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardProfileRouteChildren {
  DashboardProfileNotificationsRoute: typeof DashboardProfileNotificationsRoute
  DashboardProfilePreferencesRoute: typeof DashboardProfilePreferencesRoute
  DashboardProfileSecurityRoute: typeof DashboardProfileSecurityRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
}

const DashboardProfileRouteChildren: DashboardProfileRouteChildren = {
  DashboardProfileNotificationsRoute: DashboardProfileNotificationsRoute,
  DashboardProfilePreferencesRoute: DashboardProfilePreferencesRoute,
  DashboardProfileSecurityRoute: DashboardProfileSecurityRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
}

const DashboardProfileRouteWithChildren =
  DashboardProfileRoute._addFileChildren(DashboardProfileRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsApiKeysRoute: typeof DashboardSettingsApiKeysRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsIntegrationsRoute: typeof DashboardSettingsIntegrationsRoute
  DashboardSettingsInvoicesRoute: typeof DashboardSettingsInvoicesRoute
  DashboardSettingsMembersRoute: typeof DashboardSettingsMembersRoute
  DashboardSettingsRolesRoute: typeof DashboardSettingsRolesRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsUsageRoute: typeof DashboardSettingsUsageRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsApiKeysRoute: DashboardSettingsApiKeysRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsIntegrationsRoute: DashboardSettingsIntegrationsRoute,
  DashboardSettingsInvoicesRoute: DashboardSettingsInvoicesRoute,
  DashboardSettingsMembersRoute: DashboardSettingsMembersRoute,
  DashboardSettingsRolesRoute: DashboardSettingsRolesRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardSettingsUsageRoute: DashboardSettingsUsageRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAiChatRoute: typeof DashboardAiChatRoute
  DashboardAiToolsRoute: typeof DashboardAiToolsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardFilesRoute: typeof DashboardFilesRoute
  DashboardIdeaHubRoute: typeof DashboardIdeaHubRoute
  DashboardMeetingRoute: typeof DashboardMeetingRoute
  DashboardMilestonesRoute: typeof DashboardMilestonesRoute
  DashboardProfileRoute: typeof DashboardProfileRouteWithChildren
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardTeamChatRoute: typeof DashboardTeamChatRoute
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiChatRoute: DashboardAiChatRoute,
  DashboardAiToolsRoute: DashboardAiToolsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardFilesRoute: DashboardFilesRoute,
  DashboardIdeaHubRoute: DashboardIdeaHubRoute,
  DashboardMeetingRoute: DashboardMeetingRoute,
  DashboardMilestonesRoute: DashboardMilestonesRoute,
  DashboardProfileRoute: DashboardProfileRouteWithChildren,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardTeamChatRoute: DashboardTeamChatRoute,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
